name: Deploy PRODUÇÃO

on:
  push:
    tags: ["v*.*.*"]

concurrency:
  group: "deploy-prod-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.tag.outputs.version }}

    steps:
      - uses: actions/checkout@v6

      - name: Get Tag
        id: tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "8.0.x"

      - run: dotnet restore ./src/Api/Api.csproj
      - run: dotnet build ./src/Api/Api.csproj --configuration Release
      - run: dotnet test ./src/Api/Api.csproj --configuration Release
      - run: dotnet publish ./src/Api/Api.csproj --configuration Release --output ./publish

      - uses: actions/upload-artifact@v5
        with:
          name: build
          path: ./publish/

  deploy-prod:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: build
          path: ./publish/

      - run: |
          echo "✅ DEPLOY DE ${{ needs.build.outputs.version }} APROVADO E EXECUTADO"
